#ifndef SETTINGS_H

#define WINDOW_WIDTH 256
#define WINDOW_HEIGHT 160

#define WINDOW_POSX 50
#define WINDOW_POSY 50

#define TARGET_FRAMERATE 60.0f

#define APP_NAME "SonicInput"

#define INPUT_DEVICE 1

#define TRANSPARENT_COLOUR 0x00010101
// #define TRANSPARENT_COLOUR 0x00AAAAAA

#define SETTINGS_H
#endif